#!/usr/bin/awk -f

#Peter Mangelsdorf
#Henry Dang
#Prof. Will Mongan
#CS 265
#Final Project

#clean1.awk
#Finds and removes extraneous strings from ical file and returns an, "ical_clean" file.

#Beware Meta character: ^M

* AWK Notes
** Debugging
 - https://www.gnu.org/software/gawk/manual/html_node/Debugger.html
** Examples
 - https://en.wikibooks.org/wiki/An_Awk_Primer/Awk_Command-Line_Examples
 - https://www.tecmint.com/write-shell-scripts-in-awk-programming/
** User Manual
 - https://www.gnu.org/software/gawk/manual/gawk.html
* Emacs Notes
** General Config
 - https://www.cs.bu.edu/teachiang/tool/emacs/programming/
** AWK IT
 - https://www.emacswiki.org/emacs/AWK_It
 - https://unix.stackexchange.com/questions/197130/how-to-use-awk-it-in-emacs
** Fly Checking
 - https://www.emacswiki.org/emacs/WcheckMode
