#!/usr/bin/awk -f

#generate_table.awk
#Accepts input from generate_table.sh and appends <tr> and <\tr> to appropriate lines to build the columns within the table.
#generate_table.sh depends on generate_table.awk. It will generate a file called `out.html`. It relies on the `headers`file generated by `get_table_headers.sh`. The `out.html` file will be the desired output, with the ics file converted into a table format that can be opened by opening the `out.html` file in Google Chrome or Mozilla Firefox.

BEGIN {
    FS = "[;:]"
}

{
    if($1 == "BEGIN" && $2 == "VEVENT"){
        print "<tr>"
    } else if($1 == "END" && $2 == "VEVENT"){
        print "</tr>"
    } else {
        # Hack that makes the first column blank so that $0 prints everything from $2 onwards
        $1=""
        print "<td>"$0"</td>"
    }
}

END {
}
